
name: Depoly D-Client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Generate output
        run: npm run gen

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'MoonSupport'
          destination-repository-name: 'dictionary-client/src/markdown-pages'
          user-email: jiwon3346@naver.com

  